all:
	gcc -Wall -o minishell minishell.c 

clean:
	rm -f minishell


upload:
		scp -r /Users/javierhonduco/Dropbox/uni/SO/OS/practica2 a0303609@guernika.lab.inf.uc3m.es:/users/alumnos-12-13/a0303609/Desktop/jaja
